#!/bin/bash

echo "正在更新服务器环境变量..."

expect -c '
set timeout 60
spawn ssh root@120.24.22.244
expect "password:"
send "Lyc001286\r"
expect "root@*"
send "cat > /var/www/lyc-ai/api/.env << \"EOF\"\r"
expect "> "
send "NODE_ENV=production\r"
expect "> "
send "PORT=3001\r"
expect "> "
send "\r"
expect "> "
send "# Database\r"
expect "> "
send "DATABASE_URL=\"file:./dev.db\"\r"
expect "> "
send "\r"
expect "> "
send "# JWT\r"
expect "> "
send "JWT_SECRET=\"Lyc001286-lyc-ai-secret-key-2024\"\r"
expect "> "
send "\r"
expect "> "
send "# API Keys\r"
expect "> "
send "DEEPSEEK_API_KEY=\"sk-83f5b8ff34ea4a5aa554261d47b44b1d\"\r"
expect "> "
send "TONGYI_API_KEY=\"sk-3d5e71f997104273a8f91a4cb3419305\"\r"
expect "> "
send "\r"
expect "> "
send "# OSS Configuration\r"
expect "> "
send "OSS_REGION=\"oss-cn-shenzhen\"\r"
expect "> "
send "OSS_ACCESS_KEY_ID=\"LTAI5tL4kAoHktpX8wxSm7yb\"\r"
expect "> "
send "OSS_ACCESS_KEY_SECRET=\"eJWE1oerdOayTO1o8AZOHWLIXGDal2\"\r"
expect "> "
send "OSS_BUCKET=\"lyc-typora\"\r"
expect "> "
send "\r"
expect "> "
send "# Frontend URL\r"
expect "> "
send "CLIENT_URL=\"http://120.24.22.244\"\r"
expect "> "
send "EOF\r"
expect "root@*"
send "echo \"环境变量更新完成\"\r"
expect "root@*"
send "cd /var/www/lyc-ai/api\r"
expect "root@*"
send "pm2 restart lyc-ai-api\r"
expect "root@*"
send "pm2 status\r"
expect "root@*"
send "exit\r"
expect eof
'

echo "部署完成！"