#!/bin/bash

expect << 'EOF'
set timeout 300
spawn ssh root@120.24.22.244
expect "password:"
send "Lyc001286\r"
expect "root@*"
send "cat > /etc/nginx/sites-available/lyc-ai << 'NGINX_EOF'\r"
expect "> "
send "server {\r"
expect "> "
send "    listen 80;\r"
expect "> "
send "    server_name 120.24.22.244;\r"
expect "> "
send "    \r"
expect "> "
send "    root /var/www/lyc-ai/web/dist;\r"
expect "> "
send "    index index.html;\r"
expect "> "
send "    \r"
expect "> "
send "    location / {\r"
expect "> "
send "        try_files \\$uri \\$uri/ /index.html;\r"
expect "> "
send "        add_header Cache-Control 'no-cache';\r"
expect "> "
send "    }\r"
expect "> "
send "    \r"
expect "> "
send "    location /api {\r"
expect "> "
send "        proxy_pass http://localhost:3001;\r"
expect "> "
send "        proxy_http_version 1.1;\r"
expect "> "
send "        proxy_set_header Upgrade \\$http_upgrade;\r"
expect "> "
send "        proxy_set_header Connection 'upgrade';\r"
expect "> "
send "        proxy_set_header Host \\$host;\r"
expect "> "
send "        proxy_cache_bypass \\$http_upgrade;\r"
expect "> "
send "        proxy_set_header X-Real-IP \\$remote_addr;\r"
expect "> "
send "        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;\r"
expect "> "
send "        proxy_set_header X-Forwarded-Proto \\$scheme;\r"
expect "> "
send "    }\r"
expect "> "
send "}\r"
expect "> "
send "NGINX_EOF\r"
expect "root@*"
send "nginx -t\r"
expect "root@*"
send "systemctl reload nginx\r"
expect "root@*"
send "exit\r"
expect eof
EOF

echo "Nginx配置已更新"