#!/bin/bash

echo "=== 修复 Nginx 文件上传大小限制 ==="

# 连接到服务器修复 Nginx 配置
expect -c '
set timeout 300
spawn ssh root@120.24.22.244
expect "password:"
send "Lyc001286\r"
expect "root@*"

# 备份当前配置
send "cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old\r"
expect "root@*"

# 创建新的完整 nginx.conf 配置文件
send "cat > /etc/nginx/nginx.conf << '\''EOF'\''\r"
expect "> "
send "user nginx;\r"
expect "> "
send "worker_processes auto;\r"
expect "> "
send "error_log /var/log/nginx/error.log;\r"
expect "> "
send "pid /run/nginx.pid;\r"
expect "> "
send "\r"
expect "> "
send "events {\r"
expect "> "
send "    worker_connections 1024;\r"
expect "> "
send "}\r"
expect "> "
send "\r"
expect "> "
send "http {\r"
expect "> "
send "    client_max_body_size 100M;\r"
expect "> "
send "    \r"
expect "> "
send "    log_format main '\\$remote_addr - \\$remote_user [\\$time_local] \"\\$request\" '\r"
expect "> "
send "                      '\\$status \\$body_bytes_sent \"\\$http_referer\" '\r"
expect "> "
send "                      '\"\\$http_user_agent\" \"\\$http_x_forwarded_for\"';\r"
expect "> "
send "\r"
expect "> "
send "    access_log  /var/log/nginx/access.log  main;\r"
expect "> "
send "\r"
expect "> "
send "    sendfile            on;\r"
expect "> "
send "    tcp_nopush          on;\r"
expect "> "
send "    tcp_nodelay         on;\r"
expect "> "
send "    keepalive_timeout   65;\r"
expect "> "
send "    types_hash_max_size 2048;\r"
expect "> "
send "\r"
expect "> "
send "    include             /etc/nginx/mime.types;\r"
expect "> "
send "    default_type        application/octet-stream;\r"
expect "> "
send "\r"
expect "> "
send "    include /etc/nginx/conf.d/*.conf;\r"
expect "> "
send "    include /etc/nginx/sites-enabled/*;\r"
expect "> "
send "}\r"
expect "> "
send "EOF\r"
expect "root@*"

# 确保虚拟主机配置正确
send "mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled\r"
expect "root@*"

send "cat > /etc/nginx/sites-available/lyc-ai << '\''EOF'\''\r"
expect "> "
send "server {\r"
expect "> "
send "    listen 80;\r"
expect "> "
send "    server_name 120.24.22.244;\r"
expect "> "
send "    client_max_body_size 100M;\r"
expect "> "
send "\r"
expect "> "
send "    location / {\r"
expect "> "
send "        root /var/www/lyc-ai/web/dist;\r"
expect "> "
send "        try_files \\$uri \\$uri/ /index.html;\r"
expect "> "
send "        add_header Access-Control-Allow-Origin *;\r"
expect "> "
send "    }\r"
expect "> "
send "\r"
expect "> "
send "    location /api {\r"
expect "> "
send "        proxy_pass http://localhost:3001;\r"
expect "> "
send "        proxy_http_version 1.1;\r"
expect "> "
send "        proxy_set_header Upgrade \\$http_upgrade;\r"
expect "> "
send "        proxy_set_header Connection '\''upgrade'\'';\r"
expect "> "
send "        proxy_set_header Host \\$host;\r"
expect "> "
send "        proxy_set_header X-Real-IP \\$remote_addr;\r"
expect "> "
send "        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;\r"
expect "> "
send "        proxy_set_header X-Forwarded-Proto \\$scheme;\r"
expect "> "
send "        proxy_cache_bypass \\$http_upgrade;\r"
expect "> "
send "        proxy_read_timeout 300;\r"
expect "> "
send "        proxy_connect_timeout 300;\r"
expect "> "
send "        proxy_send_timeout 300;\r"
expect "> "
send "        client_max_body_size 100M;\r"
expect "> "
send "    }\r"
expect "> "
send "}\r"
expect "> "
send "EOF\r"
expect "root@*"

# 启用站点
send "ln -sf /etc/nginx/sites-available/lyc-ai /etc/nginx/sites-enabled/\r"
expect "root@*"

# 测试配置
send "nginx -t\r"
expect "root@*"

# 重启 Nginx 服务
send "systemctl reload nginx\r"
expect "root@*"

send "echo \"Nginx 配置已更新，文件上传限制设置为 100MB\"\r"
expect "root@*"

send "exit\r"
expect eof
'

echo ""
echo "=== Nginx 文件上传大小限制修复完成！ ==="
echo "已设置 client_max_body_size 为 100MB"
echo ""