#!/bin/bash

echo "=== 终极修复方案：彻底解决文件上传限制问题 ==="

expect -c '
set timeout 300
spawn ssh root@120.24.22.244
expect "password:"
send "Lyc001286\r"
expect "root@*"

# 1. 清理vi的swap文件
send "rm -f /etc/nginx/.nginx.conf.swp\r"
expect "root@*"

# 2. 直接使用echo创建新的nginx.conf
send "echo \"user nginx;\" > /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"worker_processes auto;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"error_log /var/log/nginx/error.log;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"pid /run/nginx.pid;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"include /usr/share/nginx/modules/*.conf;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"events {\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    worker_connections 1024;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"}\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"http {\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    client_max_body_size 100M;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    client_body_buffer_size 100M;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    sendfile on;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    tcp_nopush on;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    tcp_nodelay on;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    keepalive_timeout 65;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    types_hash_max_size 4096;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    include /etc/nginx/mime.types;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    default_type application/octet-stream;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    access_log /var/log/nginx/access.log;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    include /etc/nginx/conf.d/*.conf;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"    include /etc/nginx/sites-enabled/*;\" >> /etc/nginx/nginx.conf\r"
expect "root@*"
send "echo \"}\" >> /etc/nginx/nginx.conf\r"
expect "root@*"

# 3. 创建站点配置
send "cat > /etc/nginx/sites-available/lyc-ai << '\''SITE_EOF'\''\r"
send "server {\r"
send "    listen 80;\r"
send "    server_name 120.24.22.244;\r"
send "    client_max_body_size 100M;\r"
send "\r"
send "    location / {\r"
send "        root /var/www/lyc-ai/web/dist;\r"
send "        try_files \$uri \$uri/ /index.html;\r"
send "        add_header Access-Control-Allow-Origin *;\r"
send "    }\r"
send "\r"
send "    location /api {\r"
send "        client_max_body_size 100M;\r"
send "        proxy_pass http://localhost:3001;\r"
send "        proxy_http_version 1.1;\r"
send "        proxy_set_header Upgrade \$http_upgrade;\r"
send "        proxy_set_header Connection upgrade;\r"
send "        proxy_set_header Host \$host;\r"
send "        proxy_set_header X-Real-IP \$remote_addr;\r"
send "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\r"
send "        proxy_set_header X-Forwarded-Proto \$scheme;\r"
send "        proxy_cache_bypass \$http_upgrade;\r"
send "        proxy_request_buffering off;\r"
send "        proxy_read_timeout 300;\r"
send "        proxy_connect_timeout 300;\r"
send "        proxy_send_timeout 300;\r"
send "    }\r"
send "}\r"
send "SITE_EOF\r"
expect "root@*"

# 4. 测试并重启
send "nginx -t\r"
expect "root@*"
send "systemctl restart nginx\r"
expect "root@*"

# 5. 验证
send "systemctl status nginx --no-pager | head -3\r"
expect "root@*"
send "grep client_max_body_size /etc/nginx/nginx.conf\r"
expect "root@*"
send "grep client_max_body_size /etc/nginx/sites-available/lyc-ai\r"
expect "root@*"

send "echo \"==================\"\r"
expect "root@*"
send "echo \"修复完成！\"\r"
expect "root@*"
send "echo \"文件上传限制已设置为100MB\"\r"
expect "root@*"
send "echo \"请立即测试上传功能\"\r"
expect "root@*"

send "exit\r"
expect eof
'

echo ""
echo "脚本执行完成！"
echo "请访问 http://120.24.22.244 测试文件上传功能"